spring:
  application:
    name: SCW-ORDER
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.20.128/atcrowdfinding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8462/eureka/
  instance:
    appname: SCW-ORDER
    prefer-ip-address: true

server:
  port: 7020
